name: Build & Push Docker Image

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      #  Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construire et taguer l'image
      - name: Build Docker image
        run: |
          IMAGE_NAME=front-api-bankproject
          TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG

      # 5. Pousser l'image sur Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME=front-api-bankproject
          TAG=${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$TAG
